### PR TITLE
Adding Code Analysis

### PR DESCRIPTION
**Pull request by benrick**
## Description

Adding the default GitHub code analysis check action.

### CODE REVIEW

**Review by kirkbrauer — APPROVED** [review]
Good idea, I think we should also implement linting at some point to ensure we conform to the MS standards for code style, indentation, etc.

**Comment by benrick** [comment]
Agreed! Lots of little bits we need to add in as we get the chance.

**Comment by edmistond** [comment]
I would be fine with throwing in the Roslyn analyzers package, which I find does a lot of this and we can tweak which ones we want to keep.

**Comment by kirkbrauer** [comment]
Yeah @benrick @edmistond I had noticed that, for example, the record classes in the ActivityPub project don't have correctly named properties, which is causing my Rider to assume the incorrect code style settings. We can probably fix this with a `.editorconfig` file, but I think just have a consistent style and enforcing that is easier so anyone can use whatever IDE they want to use.

**Comment by benrick** [comment]
Yes, an editorconfig will be essential. I use 95% of this. We should too.
https://github.com/dotnet/runtime/blob/main/docs/coding-guidelines/coding-style.md

@kirkbrauer or @edmistond , want to make an issue for each of those suggestions?

**Pull request merged**
