### PR TITLE
Add models and initial migration for database

### LINKED ISSUE #17: Database and Change Management for Initial Data Storage
**Is your feature request related to a problem? Please describe.**
To start implementing the WebFinger and ActivityPub specifications, we'll need to be able to store data.

**Describe the solution you'd like**

1. Check for SQLite database on application load. If it's missing, create the database with a table for the version or schema.
2. Check if we need a version update and update the schema if required.
3. If tables are empty, load some sample data.

**Additional context**
We might consider using FluentMigrator or some other Database Change Management tool. Alternately, we could maintain just a working database that we overwrite when we need an update.

### PR DESCRIPTION
**Pull request by kirkbrauer**
## Description

Added database models and EF Core configurations for the entire Mastodon database including stored procedures and materialized views. There were some issues with the `dotnet ef dbcontext scaffold`, so I have manually modified all the generated configuration files to fix those differences between what EF Core generated and the actual database. There are also some warnings about default values, which have CLR defaults and database defaults, I have chosen to ignore those warnings for now, but we can decide if those properties should be made nullable to disable those warnings.

Fixes #17 #10

## Type of change

Please delete options that are not relevant.

- [x] New feature (non-breaking change which adds functionality)
- [x] This change requires a documentation update

## How Has This Been Tested?

I have tested this migration use `dotnet ef database update` on my local machine running PostgreSQL 15.

**Test Configuration**:
* Hardware: macOS 12.6 Intel 
* SDK: 7.0.0
* PostgreSQL 15

## Checklist:

- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [x] I have commented my code, particularly in hard-to-understand areas
- [x] I have made corresponding changes to the documentation
- [x] My changes generate no new warnings
- [x] I have added tests that prove my fix is effective or that my feature works
- [x] New and existing unit tests pass locally with my changes
- [x] Any dependent changes have been merged and published in downstream modules
- [x] I have checked my code and corrected any misspellings

### CODE REVIEW

**Comment by benrick** [comment]
I'll try to run this one locally today or tomorrow. I've looked through the code already. I want to get at least one other person to try running it.

**Comment by edmistond** [comment]
I'll pull this down to my Mac tonight and see if EF will apply the updates to a clean fresh Postgres 15 instance. Guess it gives us a chance to see if they'll work on ARM, too. :)

**Comment by edmistond** [comment]
Runs clean against Postgres 15 (via Postgres.app) on my M1:

```
❯ dotnet ef database update
Build started...
Build succeeded.
Applying migration '20221125033633_InitialCreate'.
Done.
```

I see 91 tables, 3 materialized views, and 1 view.

**Review by benrick — APPROVED** [review]
Tested migration locally and accessing database from app.

**Pull request merged**
